export const SITE_TEMPLATES = {
    'lash-beauty': {
        id: 'lash-beauty',
        name: 'Lash & Beauty',
        category: 'beauty',
        desc: 'Elegante e feminino. Rosa suave com toques dourados.',
        tokens: {
            page: 'bg-white text-zinc-900 min-h-screen font-sans',
            header: 'bg-[#FFE5F1] pt-20 pb-16 px-6 text-center relative overflow-hidden',
            logoBox: 'bg-white text-[#FF1B6D] shadow-sm',
            title: 'text-zinc-900 font-bold',
            subtitle: 'text-zinc-500',
            card: 'bg-[#FFE5F1] border-none text-zinc-900 hover:scale-[1.02] transition-all',
            serviceName: 'text-[#FF1B6D] font-bold',
            price: 'text-zinc-900',
            meta: 'text-zinc-400',
            input: 'bg-[#FFE5F1] border-transparent text-zinc-900 placeholder-zinc-400 focus:bg-white focus:border-[#FF1B6D]',
            slotBtn: 'bg-white text-zinc-800 hover:bg-[#FF1B6D] hover:text-white',
            cta: 'bg-[#FF1B6D] text-white hover:opacity-90',
            badge: 'bg-[#FF1B6D]/10 text-[#FF1B6D] text-[10px]',
            backBtn: 'bg-white shadow-sm text-zinc-400 hover:text-zinc-600',
            summaryCard: 'bg-[#FFE5F1] border-none',
            footer: 'text-zinc-300',
            label: 'text-zinc-400',
        },
        defaults: {
            primaryColor: '#FF1B6D',
            secondaryColor: '#FFE5F1',
            borderRadius: '1.25rem',
            heroTitle: 'Sua beleza em boas mãos',
            heroSubtitle: 'Especialistas em design de sobrancelhas e muito mais.',
        }
    },
    'dark-luxury': {
        id: 'dark-luxury',
        name: 'Dark Luxury',
        category: 'luxury',
        desc: 'Sofisticado e premium. Preto com detalhes em rose gold.',
        tokens: {
            page: 'bg-[#0F0F0F] text-white min-h-screen font-sans',
            header: 'bg-[#0F0F0F] pt-24 pb-20 px-6 text-center relative overflow-hidden',
            headerGlow: true,
            logoBox: 'bg-[#1C1C1C] border border-[#D4AF37]/30 text-[#D4AF37] shadow-2xl',
            title: 'text-white tracking-tight font-black',
            subtitle: 'text-zinc-500',
            card: 'bg-[#1C1C1C] border border-white/5 text-white hover:border-[#D4AF37]/50',
            serviceName: 'text-white font-black uppercase tracking-wider',
            price: 'text-[#D4AF37]',
            meta: 'text-zinc-600',
            input: 'bg-[#1C1C1C] border-white/5 text-white placeholder-zinc-600 focus:border-[#D4AF37]',
            slotBtn: 'bg-[#1C1C1C] border-white/10 text-white hover:bg-[#D4AF37]',
            cta: 'bg-[#D4AF37] text-black hover:bg-[#B8962E] font-bold',
            badge: 'bg-white/5 text-[#D4AF37] text-[10px] border border-[#D4AF37]/20',
            backBtn: 'bg-white/5 text-zinc-500 hover:text-white',
            summaryCard: 'bg-[#1C1C1C] border-[#D4AF37]/20',
            footer: 'text-zinc-800',
            label: 'text-zinc-500',
        },
        defaults: {
            primaryColor: '#D4AF37',
            secondaryColor: '#1C1C1C',
            borderRadius: '0.75rem',
            heroTitle: 'Beleza refinada com exclusividade',
            heroSubtitle: 'Tratamentos de alto padrão em um ambiente reservado.',
        }
    },
    'natural-spa': {
        id: 'natural-spa',
        name: 'Natural Spa',
        category: 'wellness',
        desc: 'Clean e minimalista. Verde natural com bege.',
        tokens: {
            page: 'bg-[#FDFBF7] text-[#2D3A3A] min-h-screen font-sans',
            header: 'bg-[#FDFBF7] pt-20 pb-16 px-6 text-center border-b border-[#E5EADD]',
            logoBox: 'bg-[#E5EADD] text-[#4A5D4E] border border-[#4A5D4E]/10',
            title: 'text-[#2D3A3A] font-light tracking-tight',
            subtitle: 'text-[#6B7C7C]',
            card: 'bg-white border border-[#E5EADD] text-[#2D3A3A] hover:bg-[#F9FAF7] hover:shadow-lg',
            serviceName: 'text-[#2D3A3A] font-medium',
            price: 'text-[#4A5D4E] font-bold',
            meta: 'text-[#6B7C7C]',
            input: 'bg-white border-[#E5EADD] text-[#2D3A3A] placeholder-[#6B7C7C]/50 focus:border-[#4A5D4E]',
            slotBtn: 'bg-[#FDFBF7] text-[#4A5D4E] border-[#E5EADD] hover:bg-[#4A5D4E] hover:text-white',
            cta: 'bg-[#4A5D4E] text-[#FDFBF7] hover:opacity-90',
            badge: 'bg-[#4A5D4E]/10 text-[#4A5D4E] text-[10px] uppercase font-bold tracking-widest',
            backBtn: 'bg-[#FDFBF7] text-[#6B7C7C] hover:text-[#4A5D4E]',
            summaryCard: 'bg-white border-[#E5EADD]',
            footer: 'text-[#BDC4B1]',
            label: 'text-[#6B7C7C]',
        },
        defaults: {
            primaryColor: '#4A5D4E',
            secondaryColor: '#E5EADD',
            borderRadius: '2rem',
            heroTitle: 'Seu momento de reconexão',
            heroSubtitle: 'Relaxe e renove suas energias com nossos tratamentos holísticos.',
        }
    },
    'urban-barber': {
        id: 'urban-barber',
        name: 'Urban Barber',
        category: 'barber',
        desc: 'Masculino e moderno. Cinza escuro com laranja vibrante.',
        tokens: {
            page: 'bg-[#111111] text-white min-h-screen font-sans',
            header: 'bg-[#111111] pt-24 pb-20 px-6 text-center border-b-4 border-[#FF4D00]',
            logoBox: 'bg-[#222222] text-[#FF4D00] border-2 border-[#FF4D00]',
            title: 'text-white font-black italic uppercase tracking-tighter text-5xl',
            subtitle: 'text-zinc-400 font-bold',
            card: 'bg-[#1A1A1A] border-l-4 border-[#FF4D00] text-white hover:bg-[#222222]',
            serviceName: 'text-white font-black italic uppercase text-lg',
            price: 'text-[#FF4D00] font-black',
            meta: 'text-zinc-500',
            input: 'bg-[#222222] border-zinc-800 text-white placeholder-zinc-600 focus:border-[#FF4D00]',
            slotBtn: 'bg-[#222222] text-[#FF4D00] border border-zinc-700 hover:bg-[#FF4D00] hover:text-white',
            cta: 'bg-[#FF4D00] text-white hover:bg-[#E64600] font-black uppercase tracking-tighter',
            badge: 'bg-[#FF4D00] text-white text-[10px] font-black italic uppercase',
            backBtn: 'bg-zinc-800 text-zinc-400 hover:text-[#FF4D00]',
            summaryCard: 'bg-[#222222] border border-zinc-700',
            footer: 'text-zinc-900',
            label: 'text-zinc-500',
        },
        defaults: {
            primaryColor: '#FF4D00',
            secondaryColor: '#1A1A1A',
            borderRadius: '0',
            heroTitle: 'RESPEITA A BARBA',
            heroSubtitle: 'Estilo clássico para o homem moderno. Sem frescura.',
        }
    },
    'skin-premium': {
        id: 'skin-premium',
        name: 'Skin Premium',
        category: 'medical',
        desc: 'Médico e confiável. Azul sereno com branco puro.',
        tokens: {
            page: 'bg-[#F8FAFC] text-[#0F172A] min-h-screen font-sans',
            header: 'bg-white pt-20 pb-16 px-6 text-center border-b border-slate-100',
            logoBox: 'bg-[#E0F2FE] text-[#0284C7] shadow-sm',
            title: 'text-[#0F172A] font-semibold tracking-tight',
            subtitle: 'text-slate-500',
            card: 'bg-white border border-slate-200 text-[#0F172A] hover:border-[#0284C7]/30 hover:shadow-xl hover:shadow-slate-200/50',
            serviceName: 'text-[#0F172A] font-bold text-base',
            price: 'text-[#0369A1]',
            meta: 'text-slate-400',
            input: 'bg-slate-50 border-slate-200 text-[#0F172A] placeholder-slate-400 focus:bg-white focus:border-[#0284C7]',
            slotBtn: 'bg-white text-slate-600 border-slate-200 hover:bg-[#0284C7] hover:text-white hover:border-[#0284C7]',
            cta: 'bg-[#0284C7] text-white hover:bg-[#0369A1]',
            badge: 'bg-[#0284C7]/10 text-[#0284C7] text-[10px] font-bold',
            backBtn: 'bg-slate-50 text-slate-400 hover:text-[#0284C7]',
            summaryCard: 'bg-slate-50 border-slate-200',
            footer: 'text-slate-300',
            label: 'text-slate-400',
        },
        defaults: {
            primaryColor: '#0284C7',
            secondaryColor: '#E0F2FE',
            borderRadius: '0.5rem',
            heroTitle: 'Especialistas em Dermatologia Estética',
            heroSubtitle: 'Saúde e beleza unidas pela ciência e tecnologia.',
        }
    },
    'fitness-studio': {
        id: 'fitness-studio',
        name: 'Fitness Studio',
        category: 'fitness',
        desc: 'Energético e motivador. Vermelho energia com preto.',
        tokens: {
            page: 'bg-[#000000] text-white min-h-screen font-sans',
            header: 'bg-[#000000] pt-24 pb-20 px-6 text-center relative overflow-hidden',
            headerGlow: true,
            logoBox: 'bg-[#DD1E22] text-white shadow-2xl shadow-[#DD1E22]/20 rotate-3',
            title: 'text-white font-black italic uppercase text-6xl tracking-tight leading-none',
            subtitle: 'text-zinc-400 font-medium tracking-widest',
            card: 'bg-[#111111] border-r-8 border-[#DD1E22] text-white hover:translate-x-2 transition-transform',
            serviceName: 'text-white font-black italic uppercase',
            price: 'text-[#DD1E22] font-black text-xl italic',
            meta: 'text-zinc-500',
            input: 'bg-[#111111] border-zinc-800 text-white placeholder-zinc-600 focus:border-[#DD1E22]',
            slotBtn: 'bg-[#111111] border border-zinc-700 text-white hover:bg-[#DD1E22] hover:text-white font-bold',
            cta: 'bg-[#DD1E22] text-white hover:opacity-90 font-black italic uppercase tracking-tighter',
            badge: 'bg-[#DD1E22] text-white text-[10px] font-black italic uppercase px-2',
            backBtn: 'bg-zinc-800 text-zinc-400 hover:text-[#DD1E22]',
            summaryCard: 'bg-[#111111] border-zinc-800',
            footer: 'text-zinc-900',
            label: 'text-zinc-500',
        },
        defaults: {
            primaryColor: '#DD1E22',
            secondaryColor: '#111111',
            borderRadius: '0.25rem',
            heroTitle: 'SEM DESCULPAS',
            heroSubtitle: 'Treinamento focado no seu resultado. Sua transformação começa hoje.',
        }
    },
    'wellness-clinic': {
        id: 'wellness-clinic',
        name: 'Wellness Clinic',
        category: 'wellness',
        desc: 'Calmo e profissional. Roxo suave com lavanda.',
        tokens: {
            page: 'bg-[#FAF9FF] text-[#2E1065] min-h-screen font-sans',
            header: 'bg-white pt-24 pb-20 px-6 text-center relative overflow-hidden',
            logoBox: 'bg-[#F5F3FF] text-[#7C3AED] shadow-xl shadow-violet-100',
            title: 'text-[#2E1065] font-black italic tracking-tighter',
            subtitle: 'text-zinc-500 italic',
            card: 'bg-white border border-violet-100 text-[#2E1065] hover:border-[#7C3AED] hover:shadow-xl hover:shadow-violet-100/30',
            serviceName: 'text-[#2E1065] font-black',
            price: 'text-[#7C3AED]',
            meta: 'text-zinc-400',
            input: 'bg-[#F5F3FF] border-[#F5F3FF] text-[#2E1065] placeholder-zinc-400 focus:bg-white focus:border-[#7C3AED]',
            slotBtn: 'bg-[#F5F3FF] text-[#7C3AED] font-bold hover:bg-[#7C3AED] hover:text-white',
            cta: 'bg-[#7C3AED] text-white hover:shadow-lg shadow-violet-200',
            badge: 'bg-violet-600 text-white text-[10px] font-bold',
            backBtn: 'bg-white shadow-xl text-zinc-300 hover:text-[#7C3AED]',
            summaryCard: 'bg-[#F5F3FF] border-violet-100',
            footer: 'text-zinc-300',
            label: 'text-zinc-400',
        },
        defaults: {
            primaryColor: '#7C3AED',
            secondaryColor: '#F5F3FF',
            borderRadius: '1.5rem',
            heroTitle: 'Seu ponto de equilíbrio',
            heroSubtitle: 'Clínica de bem-estar com terapias especializadas para seu corpo e mente.',
        }
    },
    'makeup-artist': {
        id: 'makeup-artist',
        name: 'Makeup Artist',
        category: 'beauty',
        desc: 'Glamouroso e criativo. Magenta com coral.',
        tokens: {
            page: 'bg-white text-[#4A1D1F] min-h-screen font-sans',
            header: 'bg-gradient-to-br from-[#FFF5F6] to-[#FFF0F2] pt-24 pb-20 px-6 text-center relative overflow-hidden',
            logoBox: 'bg-white text-[#E11D48] shadow-2xl',
            title: 'text-[#4A1D1F] font-black tracking-tight leading-[0.9] italic',
            subtitle: 'text-[#8B4D50]',
            card: 'bg-white border-b-4 border-[#E11D48] text-[#4A1D1F] hover:bg-[#FFF5F6] transition-colors shadow-sm',
            serviceName: 'text-[#E11D48] font-black uppercase text-base tracking-widest',
            price: 'text-[#4A1D1F] font-black',
            meta: 'text-[#8B4D50]/50',
            input: 'bg-[#FFF5F6] border-transparent text-[#4A1D1F] placeholder-[#8B4D50]/40 focus:bg-white focus:border-[#E11D48]',
            slotBtn: 'bg-[#FFF5F6] text-[#E11D48] hover:bg-[#E11D48] hover:text-white transition-all',
            cta: 'bg-[#E11D48] text-white hover:opacity-90 font-black uppercase tracking-widest',
            badge: 'bg-[#E11D48]/10 text-[#E11D48] text-[9px] font-black uppercase tracking-widest border border-[#E11D48]/20',
            backBtn: 'bg-white shadow-md text-[#8B4D50] hover:text-[#E11D48]',
            summaryCard: 'bg-[#FFF5F6]/50 border-[#E11D48]/10',
            footer: 'text-[#B49193]',
            label: 'text-[#8B4D50]',
        },
        defaults: {
            primaryColor: '#E11D48',
            secondaryColor: '#FFF5F6',
            borderRadius: '0',
            heroTitle: 'A ARTE DA MAKE',
            heroSubtitle: 'Produções completas para casamentos, eventos e editoriais de moda.',
        }
    }
};

export const getColorTokens = (templateId, primary, secondary) => {
    const template = SITE_TEMPLATES[templateId] || SITE_TEMPLATES['lash-beauty'];
    const tokens = { ...template.tokens };

    Object.keys(tokens).forEach(key => {
        if (typeof tokens[key] === 'string') {
            tokens[key] = tokens[key]
                .replace(/\[primary\]/g, primary)
                .replace(/\[secondary\]/g, secondary);
        }
    });

    return tokens;
};
